services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d exampledb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
